frr defaults traditional
hostname r1
log stdout
service integrated-vtysh-config
!
interface lo
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth1
 description to r2
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
interface eth2
 description to r3
 ip ospf area 0.0.0.1
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
interface eth3
 description to r4
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
router ospf
 ospf router-id 10.255.0.1
 timers throttle spf 50 100 500
!
