frr defaults traditional
hostname isp
log stdout
service integrated-vtysh-config
!
ip route 0.0.0.0/0 blackhole
!
router bgp 65000
 bgp router-id 203.0.113.2
 neighbor 203.0.113.1 remote-as 65001
 neighbor 203.0.113.1 description r4
 !
 address-family ipv4 unicast
  network 0.0.0.0/0
  network 198.51.100.0/24
  neighbor 203.0.113.1 route-map ANY in
  neighbor 203.0.113.1 route-map ANY out
 exit-address-family
!
route-map ANY permit 10
!
