frr defaults traditional
hostname r4
log stdout
service integrated-vtysh-config
!
interface lo
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth1
 description to r1
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
interface eth2
 description to r2
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 3
!
interface eth3
 description to isp
!
router ospf
 ospf router-id 10.255.0.4
 timers throttle spf 50 100 500
 default-information originate
!
router bgp 65001
 bgp router-id 10.255.0.4
 neighbor 203.0.113.2 remote-as 65000
 neighbor 203.0.113.2 description isp
 !
 address-family ipv4 unicast
  network 10.0.40.0/24
  redistribute ospf route-map REDIST-OSPF
  neighbor 203.0.113.2 route-map FROM-ISP in
  neighbor 203.0.113.2 route-map TO-ISP out
 exit-address-family
!
ip prefix-list CORP seq 10 permit 10.0.10.0/24
!
route-map REDIST-OSPF permit 10
 match ip address prefix-list CORP
!
route-map TO-ISP permit 10
!
route-map FROM-ISP permit 10
!
